### ISSUE TITLE
Side Hide: Removes Queue functionnality

### ISSUE THREAD

**Issue by kernelb00t** [bojanraic/spicetify-extensions#1]
This extension removes the sidebar entirely. But the Queue functionnality uses this sidebar to show.
A better approach to "hide" the sidebar would be to replace any JS that spawn the sidebar by a dummy function. That would help keeping the Queue working, and by modifying the JS the user could even choose which behaviors to remove.

**Comment by bojanraic** [comment]
Thanks for the report! 
Your suggestion sounds interesting.

Personally, I don't use the queue functionality so it was not a priority to make it more advanced than what it currently is.

However, I will investigate the suggested change when I get some time.

**Comment by bojanraic** [comment]
Side-Hide has been updated to hide only the Now Playing and Friend Activity from the sidebar. Queue and Connect functionality is intact.
