### ISSUE TITLE
Not Working Properly From Today

### ISSUE THREAD

**Issue by Aseem-ibn-imthiyas** [bojanraic/spicetify-extensions#2]
### OS Version

Windows 11

### Spotify Version

Spotify for Windows (64 bit) 1.2.47.364.gf06e5cee

### Spicetify Version

Spicetify v2.38.4

### Other Spicetify Extensions Installed

Shuffle +
Adblockify
Full Screen

### Description

"Side Hide" this extension not working properly

**Comment by bojanraic** [comment]
Hi @Aseem-ibn-imthiyas! 
I think this is related to the new Spotify layout. 
Could you please try running the following: 

``` bash
spicetify config sidebar_config 0
spicetify apply
```

and let me know if it's still an issue. 
Thanks!

**Comment by bojanraic** [comment]
Made some changes that should hopefully resolve this.  WIll close this for now.

**Comment by Aseem-ibn-imthiyas** [comment]
Nope It Didn't Work Though......

Still This Sidebar Appearing.......

**Comment by bojanraic** [comment]
I am suspecting it's a local issue then. 
I tried it on Win 11 and while it does take a few seconds after opening Spotify, the sidebar gets hidden and remains hidden when changing songs, pausing and playing, etc. 
Also tried it on a completely clean re-install on macOS Sequoia and it works as expected. 


When I open About Spotify on my Mac, this is the info returned:  
```
Spotify for macOS (Intel)
1.2.48.405.gf2c48e6f
Spicetify v2.38.4
Theme: marketplace
Extensions: adblock.js, private-session.aec2327152ee83738b13.js, side-hide.5bcf4c22e2a52a54d90f.js
Custom apps: marketplace, lyrics-plus
```
If you don't see side-hide with a commit hash in your output, then it is possible the non-working version is cached by your system.
